### ISSUE TITLE
run on macOS

### ISSUE THREAD

**Issue by gegeguai** [oxwhirl/pymarl#102]
when I run on the macOS, I get the error:

[DEBUG 18:46:03] git.cmd Popen(['git', 'version'], cwd=/Users/jianghao/.Trash/pymarl, universal_newlines=False, shell=None, istream=None)
[DEBUG 18:46:03] git.cmd Popen(['git', 'version'], cwd=/Users/jianghao/.Trash/pymarl, universal_newlines=False, shell=None, istream=None)
Traceback (most recent call last):
  File "src/main.py", line 19, in <module>
    ex = Experiment("pymarl")
  File "/anaconda3/lib/python3.7/site-packages/sacred/experiment.py", line 75, in __init__
    _caller_globals=caller_globals)
  File "/anaconda3/lib/python3.7/site-packages/sacred/ingredient.py", line 57, in __init__
    gather_sources_and_dependencies(_caller_globals)
  File "/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 487, in gather_sources_and_dependencies
    sources = gather_sources(globs, experiment_path)
  File "/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 440, in get_sources_from_imported_modules
    return get_sources_from_modules(iterate_imported_modules(globs), base_path)
  File "/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 409, in get_sources_from_modules
    filename = os.path.abspath(mod.__file__)
  File "/anaconda3/lib/python3.7/posixpath.py", line 378, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Remosy** [comment]
I got the same issue today. It works after setting Python3.6.

**Comment by gegeguai** [comment]
thanks
