### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by lxqpku** [oxwhirl/pymarl#107]
Traceback (most recent call last):
File "main.py", line 19, in
ex = Experiment("pymarl")
File "/home/username/anaconda3/lib/python3.7/site-packages/sacred/experiment.py", line 75, in init
_caller_globals=caller_globals)
File "/home/username/anaconda3/lib/python3.7/site-packages/sacred/ingredient.py", line 57, in init
gather_sources_and_dependencies(_caller_globals)
File "/home/username/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 487, in gather_sources_and_dependencies
sources = gather_sources(globs, experiment_path)
File "/home/username/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 440, in get_sources_from_imported_modules
return get_sources_from_modules(iterate_imported_modules(globs), base_path)
File "/home/username/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 409, in get_sources_from_modules
filename = os.path.abspath(mod.file)
File "/home/username/anaconda3/lib/python3.7/posixpath.py", line 371, in abspath
path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Perhaps there's a problem about the path variable, how to solve it? 
Linux system, use pip install instead of docker
Thanks

**Comment by lxqpku** [comment]
This issue has been solved following the solution proposed in #78

**Comment by Rohan138** [comment]
Had the same issue, and #78 did not work for me. Instead, I upgraded sacred via pip, which worked.

**Comment by Eleanorayx** [comment]
I think this is relevant to the version of pytorch,when I use the newest v, it failed ,but the 1.6. v , it can make it.

**Comment by ZiccMe** [comment]
`pip install sacred==0.8.2`  
can solve "TypeError: expected str, bytes or os.PathLike object, not NoneType"
