### ISSUE TITLE
 => ERROR [ 9/21] RUN pip3 install numpy scipy pyyaml 

### ISSUE THREAD

**Issue by Kallin199** [oxwhirl/pymarl#118]
I have succeeded in installing SMAC and StarCraft2 but when running bash build.sh it appears:
`
 > [ 9/21] RUN pip3 install numpy scipy pyyaml matplotlib:
#12 0.352 Traceback (most recent call last):
#12 0.352   File "/usr/local/bin/pip3", line 7, in <module>
#12 0.352     from pip._internal.cli.main import main
#12 0.352   File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 57
#12 0.352     sys.stderr.write(f"ERROR: {exc}")
#12 0.352                                    ^
#12 0.352 SyntaxError: invalid syntax
------
`

**Comment by Kallin199** [comment]
Plus, I run this code in MacBook air (M1) and vscode 1.60.0. Thanks for your help!

**Comment by keenlooks** [comment]
I'm also having this same issue

EDIT: I have fixed this particular error by changing the Dockerfile line 

`RUN pip3 install --upgrade pip`
to
`RUN pip3 install --upgrade "pip < 21.0"`
