### ISSUE TITLE
Another Sacred issue

### ISSUE THREAD

**Issue by Zymrael** [oxwhirl/pymarl#15]
Running on Windows 10 

```(nn) E:\AI\pymarl>python src/main.py --config=qmix_smac --env-config=sc2 with env_args.map_name=2s3z
Traceback (most recent call last):
  File "src/main.py", line 19, in <module>
    ex = Experiment("pymarl")
  File "C:\Users\Michael\AppData\Local\conda\conda\envs\nn\lib\site-packages\sacred\experiment.py", line 75, in __init__
    _caller_globals=caller_globals)
  File "C:\Users\Michael\AppData\Local\conda\conda\envs\nn\lib\site-packages\sacred\ingredient.py", line 57, in __init__
    gather_sources_and_dependencies(_caller_globals)
  File "C:\Users\Michael\AppData\Local\conda\conda\envs\nn\lib\site-packages\sacred\dependencies.py", line 487, in gather_sources_and_dependencies
    sources = gather_sources(globs, experiment_path)
  File "C:\Users\Michael\AppData\Local\conda\conda\envs\nn\lib\site-packages\sacred\dependencies.py", line 440, in get_sources_from_imported_modules
    return get_sources_from_modules(iterate_imported_modules(globs), base_path)
  File "C:\Users\Michael\AppData\Local\conda\conda\envs\nn\lib\site-packages\sacred\dependencies.py", line 409, in get_sources_from_modules
    filename = os.path.abspath(mod.__file__)
  File "C:\Users\Michael\AppData\Local\conda\conda\envs\nn\lib\ntpath.py", line 526, in abspath
    return _getfullpathname(path)
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType
```

Any idea of what might be causing this? The conda env was prepared via requirements.txt present in the repo.

**Comment by vat0599** [comment]
@tabzraz Thanks man this took me a lot of time to debug!

**Comment by lcEverflow** [comment]
@[tabzraz](https://github.com/tabzraz) Thank you for solving my problem
