### ISSUE TITLE
Exception while running an example

### ISSUE THREAD

**Issue by GavrilovMike** [oxwhirl/pymarl#28]
Hi! 
I've a problem:
I'm truing to run an example that are described on instructions page, but after running that command 
`python3 src/main.py --config=qmix_smac --env-config=sc2 with env_args.map_name=2s3z`
The following error is appeared:
`Traceback (most recent call last):
  File "src/main.py", line 19, in <module>
    ex = Experiment("pymarl")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sacred/experiment.py", line 75, in __init__
    _caller_globals=caller_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sacred/ingredient.py", line 57, in __init__
    gather_sources_and_dependencies(_caller_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sacred/dependencies.py", line 487, in gather_sources_and_dependencies
    sources = gather_sources(globs, experiment_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sacred/dependencies.py", line 440, in get_sources_from_imported_modules
    return get_sources_from_modules(iterate_imported_modules(globs), base_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sacred/dependencies.py", line 409, in get_sources_from_modules
    filename = os.path.abspath(mod.__file__)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 378, in abspath
    path = os.fspath(path)
**TypeError: expected str, bytes or os.PathLike object, not NoneType**`
I was trying to resolve the issue with the different versions of sacred module, but no it is still failed...
All the modules versions are taken from requirements.txt file
Could you please help?
Thank you a lot!

**Comment by tabzraz** [comment]
That does indeed look like a sacred error.
Have you tried using the version of sacred from the dockerfile (forked ~2 years ago https://github.com/oxwhirl/sacred)?
Just to make sure nothing weird is going on with previous versions, could you also try deleting the results directory (where sacred is supposed to be storing files) and trying it.

**Comment by Sud0x67** [comment]
I meet with this problem too. have you solved it?

**Comment by PeterKouss** [comment]
I meet with the same problem too. Have you soled it?

**Comment by Ynjxsjmh** [comment]
I solved this by downgrading python to 3.6.8 according to https://github.com/oxwhirl/pymarl/issues/102#issuecomment-818460788.
