### ISSUE TITLE
Ubuntu18.04: pysc2.lib.remote_controller.ConnectError: Failed to connect to the SC2 websocket. Is it up?

### ISSUE THREAD

**Issue by halleanwoo** [oxwhirl/pymarl#38]
When running `python3 src/main.py --config=qmix_smac --env-config=sc2 with env_args.map_name=2s3z`, it has a error in Ubuntu18.04:
> pysc2.lib.remote_controller.ConnectError: Failed to connect to the SC2 websocket. Is it up?

What operation did I miss? 

File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/scu/pymarl/src/runners/parallel_runner.py", line 237, in env_worker
    env.reset()
  File "/home/scu/pymarl/src/runners/parallel_runner.py", line 237, in env_worker
    env.reset()
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 341, in reset
    self._launch()
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 341, in reset
    self._launch()
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 291, in _launch
    self._sc2_proc = self._run_config.start(window_size=self.window_size)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 291, in _launch
    self._sc2_proc = self._run_config.start(window_size=self.window_size)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 205, in start
    want_rgb=want_rgb, extra_args=extra_args, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 205, in start
    want_rgb=want_rgb, extra_args=extra_args, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 88, in start
    self, exec_path=exec_path, version=self.version, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 88, in start
    self, exec_path=exec_path, version=self.version, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/sc_process.py", line 143, in __init__
    self._host, self._port, self, timeout_seconds=timeout_seconds)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/sc_process.py", line 143, in __init__
    self._host, self._port, self, timeout_seconds=timeout_seconds)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 146, in __init__
    sock = self._connect(host, port, proc, timeout_seconds)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 146, in __init__
    sock = self._connect(host, port, proc, timeout_seconds)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 180, in _connect
    raise ConnectError("Failed to connect to the SC2 websocket. Is it up?")
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 180, in _connect
    raise ConnectError("Failed to connect to the SC2 websocket. Is it up?")
pysc2.lib.remote_controller.ConnectError: Failed to connect to the SC2 websocket. Is it up?
pysc2.lib.remote_controller.ConnectError: Failed to connect to the SC2 websocket. Is it up?
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/scu/pymarl/src/runners/parallel_runner.py", line 237, in env_worker
    env.reset()
  File "/home/scu/pymarl/src/runners/parallel_runner.py", line 237, in env_worker
    env.reset()
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 341, in reset
    self._launch()
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 341, in reset
    self._launch()
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 291, in _launch
    self._sc2_proc = self._run_config.start(window_size=self.window_size)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 291, in _launch
    self._sc2_proc = self._run_config.start(window_size=self.window_size)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 205, in start
    want_rgb=want_rgb, extra_args=extra_args, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 205, in start
    want_rgb=want_rgb, extra_args=extra_args, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 88, in start
    self, exec_path=exec_path, version=self.version, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 88, in start
    self, exec_path=exec_path, version=self.version, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/sc_process.py", line 143, in __init__
    self._host, self._port, self, timeout_seconds=timeout_seconds)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/sc_process.py", line 143, in __init__
    self._host, self._port, self, timeout_seconds=timeout_seconds)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 146, in __init__
    sock = self._connect(host, port, proc, timeout_seconds)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 146, in __init__
    sock = self._connect(host, port, proc, timeout_seconds)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 180, in _connect
    raise ConnectError("Failed to connect to the SC2 websocket. Is it up?")
  File "/home/scu/anaconda3/envs/pymarl-env/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 180, in _connect
    raise ConnectError("Failed to connect to the SC2 websocket. Is it up?")
pysc2.lib.remote_controller.ConnectError: Failed to connect to the SC2 websocket. Is it up?
pysc2.lib.remote_controller.ConnectError: Failed to connect to the SC2 websocket. Is it up?

**Comment by halleanwoo** [comment]
Excuse me,  it seems that the error is caused by 
`Failed to find .build.info file at path: /home/scu/pymarl/3rdparty/StarCraftII/.build.info
`
Did I miss any operation?

**Comment by halleanwoo** [comment]
sorry, it's my mistake

**Comment by Gezx** [comment]
I meet the error like you, what is the  problem?

**Comment by Zarzard** [comment]
Did you solve it? Could you please tell me your solution?thx！
