### ISSUE TITLE
 Has anyone solved the problem？“AssertionError: Agent 2 cannot perform action 0”

### ISSUE THREAD

**Issue by Gezx** [oxwhirl/pymarl#74]
Process Process-6:
Traceback (most recent call last):
  File "/home/gzx/anaconda3/envs/py/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/gzx/anaconda3/envs/py/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gzx/PycharmProjects/pymarl-master/src/runners/parallel_runner.py", line 221, in env_worker
    reward, terminated, env_info = env.step(actions)
  File "/home/gzx/anaconda3/envs/py/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 406, in step
    sc_action = self.get_agent_action(a_id, action)
  File "/home/gzx/anaconda3/envs/py/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 478, in get_agent_action
    "Agent {} cannot perform action {}".format(a_id, action)
AssertionError: Agent 2 cannot perform action 0

**Comment by jerrylin1121** [comment]
You cannot execute some action in some timestamp. The environment could get the variable `avail_action` to check which action could be performed.

```
env.get_avail_actions() # get every agents avail_action
env.get_avail_agent_actions(agent_id) # get agents_id's avail_action
```

For more detailed, you can check on https://github.com/oxwhirl/smac
