### ISSUE TITLE
problem when running build.sh

### ISSUE THREAD

**Issue by yellowos** [oxwhirl/pymarl#95]
I found a problem when I run "bash build.sh" command, the bash told me 
" ---> Running in c984724b830f
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
The command '/bin/sh -c pip3 install numpy scipy pyyaml matplotlib' returned a non-zero code: 1"

Maybe we should using:
"RUN wget https://bootstrap.pypa.io/3.5/get-pip.py
RUN python3 get-pip.py"
to replace
"RUN apt-get -y install python3-pip"?

I made the replacement and it seems run normally, if I made the replacement will cause other problem or if there are better solution to solve the bug?

**Comment by jluo93** [comment]
same problem, hope someone can help

**Comment by yellowos** [comment]
> 同样的问题，希望有人能帮忙

兄弟，你用我的方法吧，目前看起来对付能使

**Comment by craftsliu** [comment]
It work for me,but should change to 
"RUN wget https://bootstrap.pypa.io/pip/3.5/get-pip.py
RUN python3 get-pip.py"

**Comment by Derekabc** [comment]
Step 11/27 : RUN wget https://bootstrap.pypa.io/3.5/get-pip.py
 ---> Running in 851ca46dbdae
--2021-07-30 14:14:27--  https://bootstrap.pypa.io/3.5/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.0.175, 151.101.64.175, 151.101.128.175, ...
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.0.175|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-30 14:14:27 ERROR 404: Not Found.

**Comment by farrukh-aftab-ahmed** [comment]
pip has dropped support for Python 2 and 3.5. You will need to use a version-specific branch, assuming that your Python version is 3.5:
Replace 
`RUN apt-get -y install python3-pip
RUN pip3 install --upgrade pip`
With 
`curl -fsSL -o- https://bootstrap.pypa.io/pip/3.5/get-pip.py | python3.5`
