### ISSUE TITLE
problem in MacbookPro

### ISSUE THREAD

**Issue by gegeguai** [oxwhirl/pymarl#96]
[DEBUG 09:50:54] git.cmd Popen(['git', 'version'], cwd=/Users/jianghao/Desktop/code/pymarl-master, universal_newlines=False, shell=None, istream=None)
[DEBUG 09:50:54] git.cmd Popen(['git', 'version'], cwd=/Users/jianghao/Desktop/code/pymarl-master, universal_newlines=False, shell=None, istream=None)
Traceback (most recent call last):
  File "/Users/jianghao/Desktop/code/pymarl-master/src/main.py", line 19, in <module>
    ex = Experiment("pymarl")
  File "/anaconda3/lib/python3.7/site-packages/sacred/experiment.py", line 80, in __init__
    _caller_globals=caller_globals)
  File "/anaconda3/lib/python3.7/site-packages/sacred/ingredient.py", line 55, in __init__
    gather_sources_and_dependencies(_caller_globals, self.base_dir)
  File "/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 487, in gather_sources_and_dependencies
    sources = gather_sources(globs, base_dir)
  File "/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 438, in get_sources_from_imported_modules
    return get_sources_from_modules(iterate_imported_modules(globs), base_path)
  File "/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 407, in get_sources_from_modules
    filename = os.path.abspath(mod.__file__)
  File "/anaconda3/lib/python3.7/posixpath.py", line 378, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by gegeguai** [comment]
[DEBUG 09:50:54] git.cmd Popen(['git', 'version'], cwd=/Users/jianghao/Desktop/code/pymarl-master, universal_newlines=False, shell=None, istream=None)
[DEBUG 09:50:54] git.cmd Popen(['git', 'version'], cwd=/Users/jianghao/Desktop/code/pymarl-master, universal_newlines=False, shell=None, istream=None)
Traceback (most recent call last):
  File "/Users/jianghao/Desktop/code/pymarl-master/src/main.py", line 19, in <module>
    ex = Experiment("pymarl")
  File "/anaconda3/lib/python3.7/site-packages/sacred/experiment.py", line 80, in __init__
    _caller_globals=caller_globals)
  File "/anaconda3/lib/python3.7/site-packages/sacred/ingredient.py", line 55, in __init__
    gather_sources_and_dependencies(_caller_globals, self.base_dir)
  File "/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 487, in gather_sources_and_dependencies
    sources = gather_sources(globs, base_dir)
  File "/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 438, in get_sources_from_imported_modules
    return get_sources_from_modules(iterate_imported_modules(globs), base_path)
  File "/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 407, in get_sources_from_modules
    filename = os.path.abspath(mod.__file__)
  File "/anaconda3/lib/python3.7/posixpath.py", line 378, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
